# Generated by Django 5.0.4 on 2025-12-27 04:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('department', models.CharField(max_length=100)),
                ('assigned_to', models.CharField(blank=True, max_length=100, null=True)),
                ('purchase_date', models.DateField()),
                ('warranty_expiry', models.DateField()),
                ('location', models.CharField(max_length=100)),
                ('is_scrapped', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='MaintenanceTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('members', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MaintenanceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('request_type', models.CharField(choices=[('COR', 'Corrective'), ('PRE', 'Preventive')], max_length=3)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('PRO', 'In Progress'), ('REP', 'Repaired'), ('SCR', 'Scrap')], default='NEW', max_length=3)),
                ('scheduled_date', models.DateField(blank=True, null=True)),
                ('duration_hours', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_technician', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gear.equipment')),
                ('maintenance_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Gear.maintenanceteam')),
            ],
        ),
        migrations.AddField(
            model_name='equipment',
            name='maintenance_team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Gear.maintenanceteam'),
        ),
    ]
